version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 7502
      POSTGRES_DB: todo_app_db2
    ports:
      - 5433:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8083:8080