version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 7502
      POSTGRES_DB: todo_app_db2
      JDBC_DATABASE_URL: jdbc:postgresql://db:5432/todo_app_db2
    ports:
      - 5433:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8087:8080
      
  app:
    image: todolist334
    ports:
     - 8089:8089